#versioning is obsolete and that's why i have not included it, #version-top-level-element-obsolete

services:
  db:
    image: postgres:15
    container_name: dev_task_go_lang-db
    restart: "no"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: dev_task_go_lang-app
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["/app/entrypoint.sh"]

volumes:
  pgdata:
